---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBz11weL8ooaKcYmvxbu6b1z+pg9e0rmHQheV/vrVHuNnanUpqafRAIqPlj8i4TohoSAE3dAXU9+znuwJAPXE0R8ZDEksz74ZBytJox6izEMX78R+074xygd+E4SVSVB31an5h1TOBlXxFph6Oqgxf0rxrqqfTNJxt42Zvq61O6gQkAXTcNzAIyuZdWg60ZksZ9Bfv4M0Xv14uimKJWuL6HGPm6Ymip9/IvpKz+j0sNfsca0Xz3WTRaNkBiEyVwU3j+Tl0tfszZFlKPFrYJP90SRTFFqg8e0zL4Kj5sbbeV1ZSynjsIzL9t9TqireJJhH2sB6WK49S0Ksb6pniyqIbRMfzJ9yVkI6EpfYyMIjp8/nQ/TF9y00L//INlwDtQutiMLw4wz6fToeSq+VhkRzizZaSsNdvmkIAv7SOsKjSATZQ+arP8zuYWJJ80HR9RQ8IKZ1Qx03xWRlysW2jUdZ8kRG5YoxhJEIFOwXhozTURKQmsAhyKTehcev0taAkFqk+5wk0HIs56+28U0FasO1hCi+B7c3lZh6Fq7qMSWczOkzB4YfPnnlRZzI6/OKUIB7oyuH2rNxpU8m2d7DBMQ3bh9j3p5opUPzPxX+i28/T3x/alhe4+Q6jlc2oMPUADVGUnPyzwSzFzE7LdXu/PuylNAPI4eW+hxcLhZlTiv9sRoelbfV9ux85NOvCVzQrAmvxeVOuJKcw3cXP/4i9cAvVN
  template:
    metadata:
      name: argocd-initial-admin-secret
      namespace: argocd
    type: Opaque
