---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBN/z5kE2bpmXGic7aQX2nGWwY8eWQ+uLn2/oKLtvSA4kFBETOxVF+Fjkb+q4LvVKaAt57wJzSSgW88DXWOFUQ3HV7pW/6/0NFbr7B6ODjuvJsgJV/6MOenX4vfSazsJ2FKkuL8QGyCGTpj+cHs+glwkrw/SBKO74GRyolBpawSxD8O/pwUt9c/wlw2oWMAvggNarWs5K9D00ZgWGwfXbJ63bpQl1gJQAaPJYO5l11LlH6hs/wyG1l54Bc0e+cCtIn4XMzu7ucFjG3UZfgq2gCtMWbxtTpeCArNWu56T5HwgRCtoigZeUbRFtJWHOT3x+HD2ty9ck3vLi5A/1jB9NCH4qa+HZ4sTf1mhWBl/Xq2JF1ihEjUIjrckxMZOpv86BeRGWJDVu4vQQ7yNTuGaysabTOK/I0KTGxOp2eCimexIV3bR7VtmbrfFSGwhBvTNj5I4TGIp+VkQReNs33d+Q22wTW7cbs/46nVqpCkWn4nVOnYxhu1gFU0+1cQQ7y+J6d/n5fEiIrv7yQnQd1NLQxXf4bTYJpULHOuyavO4CWDxaNR5UmXnKhG2lPKBECG24wQ5a26L8iNXvsiU2Q2xEydiUQ+mITG/Wsx7TAGkXR1mhuKU1qx7QJuMJT9TUEQKBpTGQJuABldFxYnAThNp4/EFBtBx9cRb4n5o1bmal2yStNlCZi34ywPJm28PIqbnWuvEiwRxMCLbskLL4Xsf4Nb1kRtlBOln4QpD0ZYq8dGyh4ThaOM67SkkQ1qm0e5BIsJ9Tk1spvyf79KbGuV0orrTtV+Oq1WNFPd03kEjdlxBvaIjmBDNAGFa1mLIAFBkFXW7IF79nfvKnvpsJFWM+1bZB7PISi17roqjB64aFhn532o1+0BiNnnlJw7LgsG2Sm6gIMAutoz3Q8oPbINcuvN+TEfktTbHNDMb1MORhX50Xk=
  template:
    metadata:
      name: ghcr-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
