---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgCU5XTEKo7Q1cSYsWk2EmJNuecaM1Op6wMGqAHddMO8cwA3xmRpqzoge7rUEuZV7VRLdYP92S7uwu5eKoImCbqIDApaZSrrV9+V9sUNPUOxxFJ4WbOxlUeVY4jSpP781VfSjBu56sr74Ju0FS939Z14INOUygmNZzwOnvBA9gZjwXrO4cz+kUF2GIyV+xadVFoUsjXd4u2rKrcgfW2dQ1Pq41Jlsx8U8KAxYH3e7PzgWhX79kvcGmelTCywVo2pVO9W/vSIFcfH1QbzE/c6x+XLYp6zFMhZhMUht5VkhEWUrjDLLiArECxU895+nyI4v6FCKYKygJAY2gxCpzJhXT8H02zBX6N1SjDpLzFPtgjKbDHJJvAYxBqaIBJa9/e/eFP7P8I37svflk8owl/Eb2Hc3KXtKPJ79Pg7X7MpLVdfKLIz4XoIKhFCsn9nG1kFN08pyGMrfkuoQ9r9uBy3XmVtfQn0eQPPxYWogCmb/Nu3YD4SCNHJXlhIoyUYR0s9Ds3xGyri5H1Nv8KDog3G2Bv8qAjKrUW7AQtYatJobmFkyCdJwB7AZ5/2O4VRKxTzlOhXUUloWQ7BELKAyG3GaFWBSja5l0iqUcv4qRpKjcgIayBxpBnbw5XBBlwd42ae9EvPsD6JG5FNSUyKBcjf3fRgwjdsjteeRT7cvGJ8/FpRPvrR7xNNlpkiPtcTTbW2vfN2IMbBDvceg5oSz1lfW4TxYiqK/0gYyatp3r0XmMsqZWj/nZUEe0N1iuiVUOGaoy11vpHch97BOijLQaueesXL8yZqneUlmQgnjncPgIU/E+YUTcpSoDEkGPIpDK4=
    username: AgC4FFUF9TaN9f/LdIO092pORskEGUYt6tbiHbNgRBrSbdUf97uLzctUSg4Zg27mkgrmwXWZEoCXIA7GCcFHbpA0BNIr6g0wqWtbZjnaWzM1dfnGmslVc62vdAQbRJ70i7cKdUdnDNTG/zyx4unkIbr4HTPjJK+KNO2oImcjv+Qe63s1ptiIPMJaHoSO9YvRJResA1monaTr30IzaZLTXxoV0mFnsP11fMJkEWNQcYLoyGoNgrilDu9CXIju02cGTCMCMAol4HsA6S+XyQx2AQMemo37yZsZLOll7gQktD2VgIG44g5Ab43LaZ3Snbr3k7NrpHY0JCj3zxCM1KJk/hd51Dpk9SRjKkqP2XRhRkM11thDVEBQtJRNudiUYstB5bNvrohx1Q00kFW7Xi7MJ95T69i7Lcv55JtPs73DA8wS04Mxju+ljf7Yat09HT0Sbq/Je3A9Tvw/hz2Wk6eYgNVLquQE7840MN+CdwNFov/E2n485nUFeZFUCdrGenqcfBjPvvfmiCaUidctzPguWzLwATbapL+cUl5ydmw/YohFeoHPXVyJ2ftz2aBqwcJQWRHf7W7y4RMGzbp3bxGy1kX7Mh6CIxDc3IqmtQPaJStTKef7SbcsuAf61BJKTzxzqL2Ul+R2KGXWIW8GwuoipiDAaDTmqmuYF2f7DX1sGEKuOdhBO5XDAYd4qnTOPg3I+Sj+MCFgE8h+KA==
  template:
    metadata:
      name: git-creds
      namespace: argocd
    type: Opaque
