apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "10.1.128.0/26"

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-cp-1
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-cp-1
  bgpInstances:
    - name: main
      localASN: 65201
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.0"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-cp-2
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-cp-2
  bgpInstances:
    - name: main
      localASN: 65202
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.2"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-cp-3
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-cp-3
  bgpInstances:
    - name: main
      localASN: 65203
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.6"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-worker-1
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-worker-1
  bgpInstances:
    - name: main
      localASN: 65204
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.8"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-worker-2
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-worker-2
  bgpInstances:
    - name: main
      localASN: 65205
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.10"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-url-shortener-worker-3
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: url-shortener-worker-3
  bgpInstances:
    - name: main
      localASN: 65206
      peers:
        - name: mikrotik
          peerASN: 64513
          peerAddress: "10.0.217.12"
          peerConfigRef:
            name: mikrotik-peer-config

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: mikrotik-peer-config
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels: {}

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-services
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector: {}

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidrs
spec:
  advertisements:
    - advertisementType: PodCIDR
