apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.17.1
      helm:
        valuesObject:
          kubeProxyReplacement: true
          k8sServiceHost: "localhost"
          k8sServicePort: "7445"
          ipam:
            mode: kubernetes
          bgpControlPlane:
            enabled: true
          bpf:
            masquerade: true
          routingMode: native
          autoDirectNodeRoutes: false
          ipv4NativeRoutingCIDR: "10.244.0.0/16"
          loadBalancer:
            mode: dsr
            algorithm: maglev
          operator:
            replicas: 1
          hubble:
            relay:
              enabled: true
            ui:
              enabled: false
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup
          securityContext:
            capabilities:
              ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
    - repoURL: https://github.com/kerbatek/gitops.git
      targetRevision: testing
      path: k8s/overlays/testing/infra/cilium
