resources:
  - ../../../argocd/apps/argocd-image-updater.yaml
  - ../../../argocd/apps/argocd.yaml
  - ../../../argocd/apps/cert-manager.yaml
  - ../../../argocd/apps/filebrowser.yaml
  - ../../../argocd/apps/ingress-nginx.yaml
  - ../../../argocd/apps/kube-prometheus-stack.yaml
  - ../../../argocd/apps/longhorn.yaml
  - ../../../argocd/apps/metallb.yaml
  - ../../../argocd/apps/portfolio.yaml
  - ../../../argocd/apps/sealed-secrets.yaml
  - ../../../argocd/apps/secrets.yaml

patches:
  - path: patches/argocd.yaml
  - path: patches/ingress-nginx.yaml
  - path: patches/kube-prometheus-stack.yaml
  - path: patches/metallb.yaml
  - path: patches/filebrowser.yaml
  - path: patches/portfolio.yaml
