apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: portfolio=ghcr.io/kerbatek/portfolio
    argocd-image-updater.argoproj.io/portfolio.update-strategy: latest
    argocd-image-updater.argoproj.io/portfolio.allow-tags: "regexp:^sha-[a-f0-9]+$"
    argocd-image-updater.argoproj.io/portfolio.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/git-creds"
spec:
  project: default
  source:
    repoURL: https://github.com/kerbatek/gitops.git
    targetRevision: main
    path: charts/portfolio
    helm:
      valuesObject:
        replicas: 3
        image:
          tag: "sha-4a8109d"
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
