---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCrHp20SfRNmp5czdN8jFB/xyp6LW1FcBxiWU8jPkFVGc0DZduqCiVywo6Hu7Uuastj4wn5cOhIvhN008A3E4BhkZOwnO1fsXVZ2amNATDO47+lClLYTKKUTni7g6/wR49ccj3//uKsn0UYx4L8uIWDQa+WuWT9HY/0Vqp0bE/BeADXm4DmKCkqv6Y1jzOXTYJ6+BDOVrTBKIdXF2pNMIKCHWrkTrHdQZU9yx2SiiOvDPxOYx+LGPWZE9xTXZYPHBQqpwHKRqKZGIxVLXhdG6yfWFHNjL3IxqZuApDvcR3IqwkQmgdDTAs08en/vhFkaj0OfWarZf/pNm4gqziEk4+cvmMKw5LP1ihbGSVchHmY2WeMShaGOAot48+t9VPJO8cDrP06fUKMBdGg5nEIpHR55UpJlMh3tZUcAW8dXDCid+gE5L2Mgsxw00qwzaGgBfCy8tBy+pXYaul77qTthceAbsNy6E4Fty+93T5N2BiA5dseaNX0oJQph4jVcbzhst/uOpwjTRfUhJgG4LzH60eJz18h7Zh+9ZxiCOzmRB5siDId3nv7h6Yo2nUbpBhg8/7kzW/kf0hFwYPyImskDjOvV9HLfXfGXdH4BmnfUibzVCSL0z4HAAq7yMI2wzc69rx34TQFqwoSVx07NqNLS3MEqpqe1rIefsib5tM3Ex2TROcEJ0NpnZEANDsD1WurvXpCkSL4zSXPFWvNjEB59s8v3Q083bVTdkf4
    admin-user: AgBuEYhC1PrQYkK86kQtFxOIW7xoxaIIQerLlqseD7a7+Rdz3GvoO1ykyevxwEYFcvAzd4zF+WZp6ZPcPKDJEh4NTzEjVHjI04OsKjcUzzkvovmW7K4C3bbAI13nVtyaRzdZA5GKqID1hbFmtrAAXsOS/L4tHV4oqEbqgy4pNUUnA59oBGFG6ZoLbRahTzhEs4yza+YroHTQOVrlu2b2R9FPFLedEHVQ6HnwPXUlMGoB/yv3EGMKXK1tH4tMbc2+Z+4NNDOL4asYqnnh+vC6S3pzqdI9kzohiqCW0A9cxGI0vewny3EXahW53PjkL+89QUZu0T1m7Kn6dtEyp/D9SmCYjAtakqnt/d1nzsrwDt9iu6SO29BDCKbY/F/evUXUv87HTNr4oelShni6fUbWyQ3bHjy2enVB1ADUYMjkgVpxYt1OFmW1v4mVS5i4tdQdXEI48oxfJptLqIe0N1QKQQC/2A9ZZ+Ady+/qfuvXMF7Vwi+O7957FNxZlfpT0B3ZZ9hfNWoRihDkDRGErP554mhTSqNbx7s5ejlyJAiVKet8ZAyD6ccaoKye0MNCGJTExX6oqgittBI1v7+4B7lpD46jtaBgFQ5Nh9NaYo19XfOhrTPF9dv9SuJS8JAi7QVlWMXcsmhDvUrV2AOa09k4Lg/ukO3W4xRoDTlpXXi7vSVnuAJ8YF3AmVVlbDrRznD0EYZ9/Csr/g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
