helm:
  parameters:
  - name: frontend.image.repository
    value: ghcr.io/kerbatek/portfolio-frontend
    forcestring: true
  - name: frontend.image.tag
    value: sha-6aece2c
    forcestring: true
  - name: backend.image.repository
    value: ghcr.io/kerbatek/portfolio-backend
    forcestring: true
  - name: backend.image.tag
    value: sha-6aece2c
    forcestring: true
