apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: portfolio
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
  applicationRefs:
    - namePattern: "portfolio"
      images:
        - alias: "frontend"
          imageName: "ghcr.io/kerbatek/portfolio-frontend"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^sha-[a-f0-9]+$"
          manifestTargets:
            helm:
              name: "frontend.image.repository"
              tag: "frontend.image.tag"
        - alias: "backend"
          imageName: "ghcr.io/kerbatek/portfolio-backend"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^sha-[a-f0-9]+$"
          manifestTargets:
            helm:
              name: "backend.image.repository"
              tag: "backend.image.tag"
