apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.216.0/26

---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: mikrotik
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64513
  peerAddress: 10.0.215.1

---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: main
  namespace: metallb-system
spec:
  ipAddressPools:
    - main-pool
