resources:
  - ../../../../infra/cilium/config.yaml
  - ../../../../infra/cilium/coredns-configmap.yaml
  - bgp-node-configs.yaml
  - apiserver-vip.yaml

patches:
  - target:
      kind: CiliumLoadBalancerIPPool
      name: main-pool
    patch: |-
      - op: replace
        path: /spec/blocks/0/cidr
        value: "10.1.129.0/26"
  - target:
      kind: CiliumBGPClusterConfig
      name: bgp-cluster-config
    patch: |-
      $patch: delete
      apiVersion: cilium.io/v2alpha1
      kind: CiliumBGPClusterConfig
      metadata:
        name: bgp-cluster-config
