resources:
  - ../../../../infra/filebrowser

patches:
  - target:
      kind: Ingress
      name: filebrowser
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: files.testing.mrembiasz.pl
      - op: replace
        path: /spec/tls
        value: []
  - target:
      kind: PersistentVolumeClaim
      name: filebrowser-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "2Gi"
