---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA3nPXQEs1p6J3zsgzmARi9wvea3NLRH2mFm2E9t7C1CmxP+Zpz+EtlpNRlbHRR4t+EFDtXW3mJDiv/1fgYGrBOgBtEFTRNoQWilyGKc5ZFfiQsnxffEPM2F27EmvrwqcSvPnQC6y4Y+NNjw6GQ4htwrF69qrTX16RftzHnPrOL+fjjE7X89IDxoydbnU4Cn8SkLhAgwfrzr25GmpmWs8JncwNSaHV2Vl0nIh6sYtoxh+Ki9c27K7Ys2oEepxlPan8GN/Sb6FUmnbJuseFzEOqYk42sLYBKkIZUmZAIi27G/DzJ/e85TO3iNF5CTjQBBJVB0DfnK3sayUbyWw/WDAJTsR5Aq6N+NRW2knasx6GrK9iTefSXWJOx0Ic0R2cf4oqHF/h96NKGDwVVhNphNxSiYSA8FVtbvcVV/io7eaGwUeg4mP9UskK6p9QcE95PaUMBywAMYBTn+XBxdjMIy7sXqqFfgoAfDfZh8K8moUwhd3eZoomApXmMiI3yUTEBQQ9eVJW/6PoXqzFDCpbJ/WUiOOZDzo9VdGSb3CYfxhs1CPXPKOftH+a35yYX7WieWyk6nCP9zqsWIVqIeqQSTjZVPXv+4VHq3Xoa0LBnxZ4wyjIc2AaJ0gGwzgKBcdVw+eGLPe2LM1SMwysqVeoHs38qJ9/pqgFUp9MKiP+dG6kX4vpaAF+HJz6OtQ0UltxU39H8WDPLrLXMT7mXS9Mn/enDW/UjgJaxq8EH
    admin-user: AgC0bt4g1NhTrx0I//qYn0X1C4QnSTEhR456RTopZTOTZuOfXs6sTSqh9TBTYr41M6wMlI3XOnr6zb/+NXwM5lGTygbJ5ssHBuSrQOh+Rs8cRrEXRBEhZEazEjhEMHblVUpfy5gXlOffMC7J3rTLZxmqKa5550g2NtgwkS+qS498ocKq/QAGjUIrAoxyQCzf9mANWP669j2E1ZzMAHlN5xViOTBAu8mjeBacuKpa2ee+iZqsZAft8SCLxWv/A8NggIzFbVnPX8VkdZAsRVZ4cydKuVbZJ3gdryuzur+45LXFjx5f8fCadj5D37OdO2qYMUJbT8zYMroxrqNPSBOjVKNIOeunIwyPL1+66eQn3hs4LT2vto9PaKqxDEN3VYqyNWnkazOn+YGN4D4VGDZRy7m94RCsslx4dJTnxkJCipe0FYXgItf3D/gRpSV5BXcw4Zgn2aOh44/JWsTTPLB6kyJGseqnapjm/u+0OkaAS0nhaQQnXD63EYNCTTXrjpyJB1kEKyk4uXpNAUsvh94Mu2ZUz+clrH4Ktp3tDfYawlzVrg6vHPLoUrvlm70HSmIvpRatIMjS/y0yFNy0winEuofqRPMUMChaNYYBDKRs5CzE/y1eMKLuI44TeiEP1yu5gOntO7ywQrrZufx3M23Iv3ECs4E80Nxc4FUrLOj4YlkQDHicwfcoScJ6E3PIarb3B9SxMkOxQA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
